## YAML Template.
---
image: ubuntu:18.04

stages:
 - build
 - test
before_script:
 - apt-get update –qq
 - apt-get install –yqq openjdk-11-jdk ant junit
build_program:
 stage: build
 script:
  - ant compile
  - ant jar
test_program:
 stage: test
 script:
  - ant compile-test
  - ant test